"""Shared Python image primitives for Faye Image Utility components."""

from .formats import (
    EXTENSION_BY_FORMAT,
    FORMAT_BY_EXTENSION,
    FORMAT_BY_MIME,
    IMAGE_FORMAT_BY_LOGICAL,
    MIME_BY_FORMAT,
    SUPPORTED_IMAGE_FORMATS,
    ImageFormatError,
    image_format_from_path,
    normalize_image_format,
    pillow_format_to_logical,
)
from .paths import (
    OutputCollisionError,
    OutputWriteError,
    OutputWriteMode,
    write_output_bytes,
)
from .limits import (
    MAX_DECODED_IMAGE_EDGE,
    MAX_DECODED_IMAGE_PIXELS,
    MAX_FONT_INPUT_BYTES,
    MAX_IMAGE_INPUT_BYTES,
    MAX_JSON_INPUT_BYTES,
    InputLimitError,
    InputReadError,
    JsonInputError,
    decode_utf8,
    format_byte_limit,
    parse_json_text,
    read_limited_path,
    read_limited_stream,
)

from .pillow_io import (
    DecodedImage,
    Image,
    ImageDecodeError,
    ImageEncodingMetadata,
    UnsupportedImageError,
    decode_image_bytes,
    has_alpha,
    load_image_path,
)
from .pillow_output import (
    RgbColor,
    encode_image_bytes,
    parse_rgb_color,
    prepare_image_for_output,
)

__all__ = [
    "DecodedImage",
    "EXTENSION_BY_FORMAT",
    "FORMAT_BY_EXTENSION",
    "FORMAT_BY_MIME",
    "Image",
    "ImageDecodeError",
    "ImageEncodingMetadata",
    "IMAGE_FORMAT_BY_LOGICAL",
    "ImageFormatError",
    "InputLimitError",
    "InputReadError",
    "JsonInputError",
    "MIME_BY_FORMAT",
    "MAX_DECODED_IMAGE_EDGE",
    "MAX_DECODED_IMAGE_PIXELS",
    "MAX_FONT_INPUT_BYTES",
    "MAX_IMAGE_INPUT_BYTES",
    "MAX_JSON_INPUT_BYTES",
    "OutputCollisionError",
    "OutputWriteError",
    "OutputWriteMode",
    "RgbColor",
    "SUPPORTED_IMAGE_FORMATS",
    "UnsupportedImageError",
    "decode_image_bytes",
    "decode_utf8",
    "encode_image_bytes",
    "format_byte_limit",
    "has_alpha",
    "image_format_from_path",
    "load_image_path",
    "normalize_image_format",
    "parse_rgb_color",
    "parse_json_text",
    "pillow_format_to_logical",
    "prepare_image_for_output",
    "read_limited_path",
    "read_limited_stream",
    "write_output_bytes",
]
